generatorName: typescript-fetch
inputSpec: openapi.json
outputDir: ./
configOptions:
  projectName: trieve-ts-fetch-client
  supportsES6: true
  withInterfaces: true
  npmName: trieve-ts-fetch-client
  npmVersion: 0.6.9
  snapshot: false
additionalProperties:
  useSingleRequestParameter: true
  enumPropertyNaming: camelCase
