/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponseBody,
  FileDTO,
  UploadFileData,
  UploadFileResult,
} from '../models/index';
import {
    ErrorResponseBodyFromJSON,
    ErrorResponseBodyToJSON,
    FileDTOFromJSON,
    FileDTOToJSON,
    UploadFileDataFromJSON,
    UploadFileDataToJSON,
    UploadFileResultFromJSON,
    UploadFileResultToJSON,
} from '../models/index';

export interface DeleteFileHandlerRequest {
    tRDataset: string;
    fileId: string;
    deleteChunks: boolean;
}

export interface GetDatasetFilesHandlerRequest {
    tRDataset: string;
    datasetId: string;
    page: number;
}

export interface GetFileHandlerRequest {
    tRDataset: string;
    fileId: string;
}

export interface UploadFileHandlerRequest {
    tRDataset: string;
    uploadFileData: UploadFileData;
}

/**
 * 
 */
export class FileApi extends runtime.BaseAPI {

    /**
     * Delete File  Delete a file from S3 attached to the server based on its id. This will disassociate chunks from the file, but only delete them all together if you specify delete_chunks to be true. Auth\'ed user must be an admin or owner of the dataset\'s organization to delete a file.
     * Delete File
     */
    async deleteFileHandlerRaw(requestParameters: DeleteFileHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['tRDataset'] == null) {
            throw new runtime.RequiredError(
                'tRDataset',
                'Required parameter "tRDataset" was null or undefined when calling deleteFileHandler().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling deleteFileHandler().'
            );
        }

        if (requestParameters['deleteChunks'] == null) {
            throw new runtime.RequiredError(
                'deleteChunks',
                'Required parameter "deleteChunks" was null or undefined when calling deleteFileHandler().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['deleteChunks'] != null) {
            queryParameters['delete_chunks'] = requestParameters['deleteChunks'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['tRDataset'] != null) {
            headerParameters['TR-Dataset'] = String(requestParameters['tRDataset']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/api/file/{file_id}`.replace(`{${"file_id"}}`, encodeURIComponent(String(requestParameters['fileId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete File  Delete a file from S3 attached to the server based on its id. This will disassociate chunks from the file, but only delete them all together if you specify delete_chunks to be true. Auth\'ed user must be an admin or owner of the dataset\'s organization to delete a file.
     * Delete File
     */
    async deleteFileHandler(requestParameters: DeleteFileHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFileHandlerRaw(requestParameters, initOverrides);
    }

    /**
     * Get Files for Dataset  Get all files which belong to a given dataset specified by the dataset_id parameter. 10 files are returned per page.
     * Get Files for Dataset
     */
    async getDatasetFilesHandlerRaw(requestParameters: GetDatasetFilesHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<any>>> {
        if (requestParameters['tRDataset'] == null) {
            throw new runtime.RequiredError(
                'tRDataset',
                'Required parameter "tRDataset" was null or undefined when calling getDatasetFilesHandler().'
            );
        }

        if (requestParameters['datasetId'] == null) {
            throw new runtime.RequiredError(
                'datasetId',
                'Required parameter "datasetId" was null or undefined when calling getDatasetFilesHandler().'
            );
        }

        if (requestParameters['page'] == null) {
            throw new runtime.RequiredError(
                'page',
                'Required parameter "page" was null or undefined when calling getDatasetFilesHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['tRDataset'] != null) {
            headerParameters['TR-Dataset'] = String(requestParameters['tRDataset']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/api/dataset/files/{dataset_id}/{page}`.replace(`{${"dataset_id"}}`, encodeURIComponent(String(requestParameters['datasetId']))).replace(`{${"page"}}`, encodeURIComponent(String(requestParameters['page']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Files for Dataset  Get all files which belong to a given dataset specified by the dataset_id parameter. 10 files are returned per page.
     * Get Files for Dataset
     */
    async getDatasetFilesHandler(requestParameters: GetDatasetFilesHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<any>> {
        const response = await this.getDatasetFilesHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get File  Download a file based on its id.
     * Get File
     */
    async getFileHandlerRaw(requestParameters: GetFileHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileDTO>> {
        if (requestParameters['tRDataset'] == null) {
            throw new runtime.RequiredError(
                'tRDataset',
                'Required parameter "tRDataset" was null or undefined when calling getFileHandler().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling getFileHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['tRDataset'] != null) {
            headerParameters['TR-Dataset'] = String(requestParameters['tRDataset']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/api/file/{file_id}`.replace(`{${"file_id"}}`, encodeURIComponent(String(requestParameters['fileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileDTOFromJSON(jsonValue));
    }

    /**
     * Get File  Download a file based on its id.
     * Get File
     */
    async getFileHandler(requestParameters: GetFileHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileDTO> {
        const response = await this.getFileHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload File  Upload a file to S3 attached to the server. The file will be converted to HTML with tika and chunked algorithmically, images will be OCR\'ed with tesseract. The resulting chunks will be indexed and searchable. Optionally, you can only upload the file and manually create chunks associated to the file after. See docs.trieve.ai and/or contact us for more details and tips. Auth\'ed user must be an admin or owner of the dataset\'s organization to upload a file.
     * Upload File
     */
    async uploadFileHandlerRaw(requestParameters: UploadFileHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadFileResult>> {
        if (requestParameters['tRDataset'] == null) {
            throw new runtime.RequiredError(
                'tRDataset',
                'Required parameter "tRDataset" was null or undefined when calling uploadFileHandler().'
            );
        }

        if (requestParameters['uploadFileData'] == null) {
            throw new runtime.RequiredError(
                'uploadFileData',
                'Required parameter "uploadFileData" was null or undefined when calling uploadFileHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['tRDataset'] != null) {
            headerParameters['TR-Dataset'] = String(requestParameters['tRDataset']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/api/file`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UploadFileDataToJSON(requestParameters['uploadFileData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadFileResultFromJSON(jsonValue));
    }

    /**
     * Upload File  Upload a file to S3 attached to the server. The file will be converted to HTML with tika and chunked algorithmically, images will be OCR\'ed with tesseract. The resulting chunks will be indexed and searchable. Optionally, you can only upload the file and manually create chunks associated to the file after. See docs.trieve.ai and/or contact us for more details and tips. Auth\'ed user must be an admin or owner of the dataset\'s organization to upload a file.
     * Upload File
     */
    async uploadFileHandler(requestParameters: UploadFileHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadFileResult> {
        const response = await this.uploadFileHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
