/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddChunkToGroupData
 */
export interface AddChunkToGroupData {
    /**
     * Id of the chunk to make a member of the group.
     * @type {string}
     * @memberof AddChunkToGroupData
     */
    chunkId?: string;
    /**
     * Tracking Id of the chunk to make a member of the group.
     * @type {string}
     * @memberof AddChunkToGroupData
     */
    trackingId?: string;
}

/**
 * Check if a given object implements the AddChunkToGroupData interface.
 */
export function instanceOfAddChunkToGroupData(value: object): boolean {
    return true;
}

export function AddChunkToGroupDataFromJSON(json: any): AddChunkToGroupData {
    return AddChunkToGroupDataFromJSONTyped(json, false);
}

export function AddChunkToGroupDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddChunkToGroupData {
    if (json == null) {
        return json;
    }
    return {
        
        'chunkId': json['chunk_id'] == null ? undefined : json['chunk_id'],
        'trackingId': json['tracking_id'] == null ? undefined : json['tracking_id'],
    };
}

export function AddChunkToGroupDataToJSON(value?: AddChunkToGroupData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chunk_id': value['chunkId'],
        'tracking_id': value['trackingId'],
    };
}

