/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChunkMetadata } from './ChunkMetadata';
import {
    ChunkMetadataFromJSON,
    ChunkMetadataFromJSONTyped,
    ChunkMetadataToJSON,
} from './ChunkMetadata';

/**
 * 
 * @export
 * @interface BatchQueuedChunkResponse
 */
export interface BatchQueuedChunkResponse {
    /**
     * 
     * @type {Array<ChunkMetadata>}
     * @memberof BatchQueuedChunkResponse
     */
    chunkMetadata: Array<ChunkMetadata>;
    /**
     * The current position the last access item is in the queue
     * @type {number}
     * @memberof BatchQueuedChunkResponse
     */
    posInQueue: number;
}

/**
 * Check if a given object implements the BatchQueuedChunkResponse interface.
 */
export function instanceOfBatchQueuedChunkResponse(value: object): boolean {
    if (!('chunkMetadata' in value)) return false;
    if (!('posInQueue' in value)) return false;
    return true;
}

export function BatchQueuedChunkResponseFromJSON(json: any): BatchQueuedChunkResponse {
    return BatchQueuedChunkResponseFromJSONTyped(json, false);
}

export function BatchQueuedChunkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchQueuedChunkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chunkMetadata': ((json['chunk_metadata'] as Array<any>).map(ChunkMetadataFromJSON)),
        'posInQueue': json['pos_in_queue'],
    };
}

export function BatchQueuedChunkResponseToJSON(value?: BatchQueuedChunkResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chunk_metadata': ((value['chunkMetadata'] as Array<any>).map(ChunkMetadataToJSON)),
        'pos_in_queue': value['posInQueue'],
    };
}

