/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SlimGroup } from './SlimGroup';
import {
    SlimGroupFromJSON,
    SlimGroupFromJSONTyped,
    SlimGroupToJSON,
} from './SlimGroup';

/**
 * 
 * @export
 * @interface BookmarkGroupResult
 */
export interface BookmarkGroupResult {
    /**
     * 
     * @type {string}
     * @memberof BookmarkGroupResult
     */
    chunkUuid: string;
    /**
     * 
     * @type {Array<SlimGroup>}
     * @memberof BookmarkGroupResult
     */
    slimGroups: Array<SlimGroup>;
}

/**
 * Check if a given object implements the BookmarkGroupResult interface.
 */
export function instanceOfBookmarkGroupResult(value: object): boolean {
    if (!('chunkUuid' in value)) return false;
    if (!('slimGroups' in value)) return false;
    return true;
}

export function BookmarkGroupResultFromJSON(json: any): BookmarkGroupResult {
    return BookmarkGroupResultFromJSONTyped(json, false);
}

export function BookmarkGroupResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkGroupResult {
    if (json == null) {
        return json;
    }
    return {
        
        'chunkUuid': json['chunk_uuid'],
        'slimGroups': ((json['slim_groups'] as Array<any>).map(SlimGroupFromJSON)),
    };
}

export function BookmarkGroupResultToJSON(value?: BookmarkGroupResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chunk_uuid': value['chunkUuid'],
        'slim_groups': ((value['slimGroups'] as Array<any>).map(SlimGroupToJSON)),
    };
}

