/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessageProxy
 */
export interface ChatMessageProxy {
    /**
     * 
     * @type {string}
     * @memberof ChatMessageProxy
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageProxy
     */
    role: string;
}

/**
 * Check if a given object implements the ChatMessageProxy interface.
 */
export function instanceOfChatMessageProxy(value: object): boolean {
    if (!('content' in value)) return false;
    if (!('role' in value)) return false;
    return true;
}

export function ChatMessageProxyFromJSON(json: any): ChatMessageProxy {
    return ChatMessageProxyFromJSONTyped(json, false);
}

export function ChatMessageProxyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessageProxy {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'role': json['role'],
    };
}

export function ChatMessageProxyToJSON(value?: ChatMessageProxy | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
        'role': value['role'],
    };
}

