/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChunkGroup
 */
export interface ChunkGroup {
    /**
     * 
     * @type {Date}
     * @memberof ChunkGroup
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ChunkGroup
     */
    datasetId: string;
    /**
     * 
     * @type {string}
     * @memberof ChunkGroup
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ChunkGroup
     */
    id: string;
    /**
     * 
     * @type {any}
     * @memberof ChunkGroup
     */
    metadata?: any;
    /**
     * 
     * @type {string}
     * @memberof ChunkGroup
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ChunkGroup
     */
    tagSet?: string;
    /**
     * 
     * @type {string}
     * @memberof ChunkGroup
     */
    trackingId?: string;
    /**
     * 
     * @type {Date}
     * @memberof ChunkGroup
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ChunkGroup interface.
 */
export function instanceOfChunkGroup(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('datasetId' in value)) return false;
    if (!('description' in value)) return false;
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function ChunkGroupFromJSON(json: any): ChunkGroup {
    return ChunkGroupFromJSONTyped(json, false);
}

export function ChunkGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChunkGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'datasetId': json['dataset_id'],
        'description': json['description'],
        'id': json['id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'],
        'tagSet': json['tag_set'] == null ? undefined : json['tag_set'],
        'trackingId': json['tracking_id'] == null ? undefined : json['tracking_id'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ChunkGroupToJSON(value?: ChunkGroup | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'dataset_id': value['datasetId'],
        'description': value['description'],
        'id': value['id'],
        'metadata': value['metadata'],
        'name': value['name'],
        'tag_set': value['tagSet'],
        'tracking_id': value['trackingId'],
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

