/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChunkData
 */
export interface ChunkData {
    /**
     * HTML content of the chunk. This can also be plaintext. The innerText of the HTML will be used to create the embedding vector. The point of using HTML is for convienience, as some users have applications where users submit HTML content.
     * @type {string}
     * @memberof ChunkData
     */
    chunkHtml?: string;
    /**
     * Chunk_vector is a vector of floats which can be used instead of generating a new embedding. This is useful for when you are using a pre-embedded dataset. If this is not provided, the innerText of the chunk_html will be used to create the embedding.
     * @type {Array<number>}
     * @memberof ChunkData
     */
    chunkVector?: Array<number>;
    /**
     * Convert HTML to raw text before processing to avoid adding noise to the vector embeddings. By default this is true. If you are using HTML content that you want to be included in the vector embeddings, set this to false.
     * @type {boolean}
     * @memberof ChunkData
     */
    convertHtmlToText?: boolean;
    /**
     * File_uuid is the uuid of the file that the chunk is associated with. This is used to associate chunks with files. This is useful for when you want to delete a file and all of its associated chunks.
     * @type {string}
     * @memberof ChunkData
     */
    fileId?: string;
    /**
     * Group ids are the ids of the groups that the chunk should be placed into. This is useful for when you want to create a chunk and add it to a group or multiple groups in one request. Necessary because this route queues the chunk for ingestion and the chunk may not exist yet immediately after response.
     * @type {Array<string>}
     * @memberof ChunkData
     */
    groupIds?: Array<string>;
    /**
     * Group tracking_ids are the tracking_ids of the groups that the chunk should be placed into. This is useful for when you want to create a chunk and add it to a group or multiple groups in one request. Necessary because this route queues the chunk for ingestion and the chunk may not exist yet immediately after response.
     * @type {Array<string>}
     * @memberof ChunkData
     */
    groupTrackingIds?: Array<string>;
    /**
     * Link to the chunk. This can also be any string. Frequently, this is a link to the source of the chunk. The link value will not affect the embedding creation.
     * @type {string}
     * @memberof ChunkData
     */
    link?: string;
    /**
     * Metadata is a JSON object which can be used to filter chunks. This is useful for when you want to filter chunks by arbitrary metadata. Unlike with tag filtering, there is a performance hit for filtering on metadata.
     * @type {any}
     * @memberof ChunkData
     */
    metadata?: any;
    /**
     * Split avg is a boolean which tells the server to split the text in the chunk_html into smaller chunks and average their resulting vectors. This is useful for when you want to create a chunk from a large piece of text and want to split it into smaller chunks to create a more fuzzy average dense vector. The sparse vector will be generated normally with no averaging. By default this is false.
     * @type {boolean}
     * @memberof ChunkData
     */
    splitAvg?: boolean;
    /**
     * Tag set is a list of tags. This can be used to filter chunks by tag. Unlike with metadata filtering, HNSW indices will exist for each tag such that there is not a performance hit for filtering on them.
     * @type {Array<string>}
     * @memberof ChunkData
     */
    tagSet?: Array<string>;
    /**
     * Time_stamp should be an ISO 8601 combined date and time without timezone. It is used for time window filtering and recency-biasing search results.
     * @type {string}
     * @memberof ChunkData
     */
    timeStamp?: string;
    /**
     * Tracking_id is a string which can be used to identify a chunk. This is useful for when you are coordinating with an external system and want to use the tracking_id to identify the chunk.
     * @type {string}
     * @memberof ChunkData
     */
    trackingId?: string;
    /**
     * Upsert when a chunk with the same tracking_id exists. By default this is false, and the request will fail if a chunk with the same tracking_id exists. If this is true, the chunk will be updated if a chunk with the same tracking_id exists.
     * @type {boolean}
     * @memberof ChunkData
     */
    upsertByTrackingId?: boolean;
    /**
     * Weight is a float which can be used to bias search results. This is useful for when you want to bias search results for a chunk. The magnitude only matters relative to other chunks in the chunk's dataset dataset.
     * @type {number}
     * @memberof ChunkData
     */
    weight?: number;
}

/**
 * Check if a given object implements the ChunkData interface.
 */
export function instanceOfChunkData(value: object): boolean {
    return true;
}

export function ChunkDataFromJSON(json: any): ChunkData {
    return ChunkDataFromJSONTyped(json, false);
}

export function ChunkDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChunkData {
    if (json == null) {
        return json;
    }
    return {
        
        'chunkHtml': json['chunk_html'] == null ? undefined : json['chunk_html'],
        'chunkVector': json['chunk_vector'] == null ? undefined : json['chunk_vector'],
        'convertHtmlToText': json['convert_html_to_text'] == null ? undefined : json['convert_html_to_text'],
        'fileId': json['file_id'] == null ? undefined : json['file_id'],
        'groupIds': json['group_ids'] == null ? undefined : json['group_ids'],
        'groupTrackingIds': json['group_tracking_ids'] == null ? undefined : json['group_tracking_ids'],
        'link': json['link'] == null ? undefined : json['link'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'splitAvg': json['split_avg'] == null ? undefined : json['split_avg'],
        'tagSet': json['tag_set'] == null ? undefined : json['tag_set'],
        'timeStamp': json['time_stamp'] == null ? undefined : json['time_stamp'],
        'trackingId': json['tracking_id'] == null ? undefined : json['tracking_id'],
        'upsertByTrackingId': json['upsert_by_tracking_id'] == null ? undefined : json['upsert_by_tracking_id'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function ChunkDataToJSON(value?: ChunkData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chunk_html': value['chunkHtml'],
        'chunk_vector': value['chunkVector'],
        'convert_html_to_text': value['convertHtmlToText'],
        'file_id': value['fileId'],
        'group_ids': value['groupIds'],
        'group_tracking_ids': value['groupTrackingIds'],
        'link': value['link'],
        'metadata': value['metadata'],
        'split_avg': value['splitAvg'],
        'tag_set': value['tagSet'],
        'time_stamp': value['timeStamp'],
        'tracking_id': value['trackingId'],
        'upsert_by_tracking_id': value['upsertByTrackingId'],
        'weight': value['weight'],
    };
}

