/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChunkGroupAndFile
 */
export interface ChunkGroupAndFile {
    /**
     * 
     * @type {Date}
     * @memberof ChunkGroupAndFile
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ChunkGroupAndFile
     */
    datasetId: string;
    /**
     * 
     * @type {string}
     * @memberof ChunkGroupAndFile
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ChunkGroupAndFile
     */
    fileId?: string;
    /**
     * 
     * @type {string}
     * @memberof ChunkGroupAndFile
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ChunkGroupAndFile
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ChunkGroupAndFile
     */
    trackingId?: string;
    /**
     * 
     * @type {Date}
     * @memberof ChunkGroupAndFile
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ChunkGroupAndFile interface.
 */
export function instanceOfChunkGroupAndFile(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('datasetId' in value)) return false;
    if (!('description' in value)) return false;
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function ChunkGroupAndFileFromJSON(json: any): ChunkGroupAndFile {
    return ChunkGroupAndFileFromJSONTyped(json, false);
}

export function ChunkGroupAndFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChunkGroupAndFile {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'datasetId': json['dataset_id'],
        'description': json['description'],
        'fileId': json['file_id'] == null ? undefined : json['file_id'],
        'id': json['id'],
        'name': json['name'],
        'trackingId': json['tracking_id'] == null ? undefined : json['tracking_id'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ChunkGroupAndFileToJSON(value?: ChunkGroupAndFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'dataset_id': value['datasetId'],
        'description': value['description'],
        'file_id': value['fileId'],
        'id': value['id'],
        'name': value['name'],
        'tracking_id': value['trackingId'],
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

