/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientDatasetConfiguration
 */
export interface ClientDatasetConfiguration {
    /**
     * 
     * @type {boolean}
     * @memberof ClientDatasetConfiguration
     */
    cREATECHUNKFEATURE?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ClientDatasetConfiguration
     */
    dATERANGEVALUE?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ClientDatasetConfiguration
     */
    dOCUMENTUPLOADFEATURE?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ClientDatasetConfiguration
     */
    fILENAMEKEY: string;
    /**
     * 
     * @type {any}
     * @memberof ClientDatasetConfiguration
     */
    fILTERITEMS?: any;
    /**
     * 
     * @type {string}
     * @memberof ClientDatasetConfiguration
     */
    fRONTMATTERVALS?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientDatasetConfiguration
     */
    iMAGERANGEENDKEY?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientDatasetConfiguration
     */
    iMAGERANGESTARTKEY?: string;
    /**
     * 
     * @type {number}
     * @memberof ClientDatasetConfiguration
     */
    lINESBEFORESHOWMORE?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientDatasetConfiguration
     */
    sEARCHQUERIES?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientDatasetConfiguration
     */
    sUGGESTEDQUERIES?: string;
}

/**
 * Check if a given object implements the ClientDatasetConfiguration interface.
 */
export function instanceOfClientDatasetConfiguration(value: object): boolean {
    if (!('fILENAMEKEY' in value)) return false;
    return true;
}

export function ClientDatasetConfigurationFromJSON(json: any): ClientDatasetConfiguration {
    return ClientDatasetConfigurationFromJSONTyped(json, false);
}

export function ClientDatasetConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientDatasetConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'cREATECHUNKFEATURE': json['CREATE_CHUNK_FEATURE'] == null ? undefined : json['CREATE_CHUNK_FEATURE'],
        'dATERANGEVALUE': json['DATE_RANGE_VALUE'] == null ? undefined : json['DATE_RANGE_VALUE'],
        'dOCUMENTUPLOADFEATURE': json['DOCUMENT_UPLOAD_FEATURE'] == null ? undefined : json['DOCUMENT_UPLOAD_FEATURE'],
        'fILENAMEKEY': json['FILE_NAME_KEY'],
        'fILTERITEMS': json['FILTER_ITEMS'] == null ? undefined : json['FILTER_ITEMS'],
        'fRONTMATTERVALS': json['FRONTMATTER_VALS'] == null ? undefined : json['FRONTMATTER_VALS'],
        'iMAGERANGEENDKEY': json['IMAGE_RANGE_END_KEY'] == null ? undefined : json['IMAGE_RANGE_END_KEY'],
        'iMAGERANGESTARTKEY': json['IMAGE_RANGE_START_KEY'] == null ? undefined : json['IMAGE_RANGE_START_KEY'],
        'lINESBEFORESHOWMORE': json['LINES_BEFORE_SHOW_MORE'] == null ? undefined : json['LINES_BEFORE_SHOW_MORE'],
        'sEARCHQUERIES': json['SEARCH_QUERIES'] == null ? undefined : json['SEARCH_QUERIES'],
        'sUGGESTEDQUERIES': json['SUGGESTED_QUERIES'] == null ? undefined : json['SUGGESTED_QUERIES'],
    };
}

export function ClientDatasetConfigurationToJSON(value?: ClientDatasetConfiguration | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'CREATE_CHUNK_FEATURE': value['cREATECHUNKFEATURE'],
        'DATE_RANGE_VALUE': value['dATERANGEVALUE'],
        'DOCUMENT_UPLOAD_FEATURE': value['dOCUMENTUPLOADFEATURE'],
        'FILE_NAME_KEY': value['fILENAMEKEY'],
        'FILTER_ITEMS': value['fILTERITEMS'],
        'FRONTMATTER_VALS': value['fRONTMATTERVALS'],
        'IMAGE_RANGE_END_KEY': value['iMAGERANGEENDKEY'],
        'IMAGE_RANGE_START_KEY': value['iMAGERANGESTARTKEY'],
        'LINES_BEFORE_SHOW_MORE': value['lINESBEFORESHOWMORE'],
        'SEARCH_QUERIES': value['sEARCHQUERIES'],
        'SUGGESTED_QUERIES': value['sUGGESTEDQUERIES'],
    };
}

