/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganizationData
 */
export interface CreateOrganizationData {
    /**
     * The arbitrary name which will be used to identify the organization. This name must be unique.
     * @type {string}
     * @memberof CreateOrganizationData
     */
    name: string;
}

/**
 * Check if a given object implements the CreateOrganizationData interface.
 */
export function instanceOfCreateOrganizationData(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function CreateOrganizationDataFromJSON(json: any): CreateOrganizationData {
    return CreateOrganizationDataFromJSONTyped(json, false);
}

export function CreateOrganizationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationData {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateOrganizationDataToJSON(value?: CreateOrganizationData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

