/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasetDTO } from './DatasetDTO';
import {
    DatasetDTOFromJSON,
    DatasetDTOFromJSONTyped,
    DatasetDTOToJSON,
} from './DatasetDTO';
import type { DatasetUsageCount } from './DatasetUsageCount';
import {
    DatasetUsageCountFromJSON,
    DatasetUsageCountFromJSONTyped,
    DatasetUsageCountToJSON,
} from './DatasetUsageCount';

/**
 * 
 * @export
 * @interface DatasetAndUsage
 */
export interface DatasetAndUsage {
    /**
     * 
     * @type {DatasetDTO}
     * @memberof DatasetAndUsage
     */
    dataset: DatasetDTO;
    /**
     * 
     * @type {DatasetUsageCount}
     * @memberof DatasetAndUsage
     */
    datasetUsage: DatasetUsageCount;
}

/**
 * Check if a given object implements the DatasetAndUsage interface.
 */
export function instanceOfDatasetAndUsage(value: object): boolean {
    if (!('dataset' in value)) return false;
    if (!('datasetUsage' in value)) return false;
    return true;
}

export function DatasetAndUsageFromJSON(json: any): DatasetAndUsage {
    return DatasetAndUsageFromJSONTyped(json, false);
}

export function DatasetAndUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetAndUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'dataset': DatasetDTOFromJSON(json['dataset']),
        'datasetUsage': DatasetUsageCountFromJSON(json['dataset_usage']),
    };
}

export function DatasetAndUsageToJSON(value?: DatasetAndUsage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dataset': DatasetDTOToJSON(value['dataset']),
        'dataset_usage': DatasetUsageCountToJSON(value['datasetUsage']),
    };
}

