/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatasetDTO
 */
export interface DatasetDTO {
    /**
     * 
     * @type {any}
     * @memberof DatasetDTO
     */
    clientConfiguration: any | null;
    /**
     * 
     * @type {Date}
     * @memberof DatasetDTO
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof DatasetDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetDTO
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetDTO
     */
    trackingId?: string;
    /**
     * 
     * @type {Date}
     * @memberof DatasetDTO
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the DatasetDTO interface.
 */
export function instanceOfDatasetDTO(value: object): boolean {
    if (!('clientConfiguration' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('organizationId' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function DatasetDTOFromJSON(json: any): DatasetDTO {
    return DatasetDTOFromJSONTyped(json, false);
}

export function DatasetDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'clientConfiguration': json['client_configuration'],
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'name': json['name'],
        'organizationId': json['organization_id'],
        'trackingId': json['tracking_id'] == null ? undefined : json['tracking_id'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function DatasetDTOToJSON(value?: DatasetDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'client_configuration': value['clientConfiguration'],
        'created_at': ((value['createdAt']).toISOString()),
        'id': value['id'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'tracking_id': value['trackingId'],
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

