/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteTopicData
 */
export interface DeleteTopicData {
    /**
     * The id of the topic to target.
     * @type {string}
     * @memberof DeleteTopicData
     */
    topicId: string;
}

/**
 * Check if a given object implements the DeleteTopicData interface.
 */
export function instanceOfDeleteTopicData(value: object): boolean {
    if (!('topicId' in value)) return false;
    return true;
}

export function DeleteTopicDataFromJSON(json: any): DeleteTopicData {
    return DeleteTopicDataFromJSONTyped(json, false);
}

export function DeleteTopicDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTopicData {
    if (json == null) {
        return json;
    }
    return {
        
        'topicId': json['topic_id'],
    };
}

export function DeleteTopicDataToJSON(value?: DeleteTopicData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'topic_id': value['topicId'],
    };
}

