/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponseBody
 */
export interface ErrorResponseBody {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseBody
     */
    message: string;
}

/**
 * Check if a given object implements the ErrorResponseBody interface.
 */
export function instanceOfErrorResponseBody(value: object): boolean {
    if (!('message' in value)) return false;
    return true;
}

export function ErrorResponseBodyFromJSON(json: any): ErrorResponseBody {
    return ErrorResponseBodyFromJSONTyped(json, false);
}

export function ErrorResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ErrorResponseBodyToJSON(value?: ErrorResponseBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

