/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    datasetId: string;
    /**
     * 
     * @type {any}
     * @memberof Event
     */
    eventData: any | null;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    eventType: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('datasetId' in value)) return false;
    if (!('eventData' in value)) return false;
    if (!('eventType' in value)) return false;
    if (!('id' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'datasetId': json['dataset_id'],
        'eventData': json['event_data'],
        'eventType': json['event_type'],
        'id': json['id'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function EventToJSON(value?: Event | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'dataset_id': value['datasetId'],
        'event_data': value['eventData'],
        'event_type': value['eventType'],
        'id': value['id'],
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

