/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileDTO
 */
export interface FileDTO {
    /**
     * 
     * @type {Date}
     * @memberof FileDTO
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof FileDTO
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof FileDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FileDTO
     */
    link?: string;
    /**
     * 
     * @type {any}
     * @memberof FileDTO
     */
    metadata?: any;
    /**
     * 
     * @type {string}
     * @memberof FileDTO
     */
    s3Url: string;
    /**
     * 
     * @type {number}
     * @memberof FileDTO
     */
    size: number;
    /**
     * 
     * @type {Date}
     * @memberof FileDTO
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the FileDTO interface.
 */
export function instanceOfFileDTO(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('fileName' in value)) return false;
    if (!('id' in value)) return false;
    if (!('s3Url' in value)) return false;
    if (!('size' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function FileDTOFromJSON(json: any): FileDTO {
    return FileDTOFromJSONTyped(json, false);
}

export function FileDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'fileName': json['file_name'],
        'id': json['id'],
        'link': json['link'] == null ? undefined : json['link'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        's3Url': json['s3_url'],
        'size': json['size'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function FileDTOToJSON(value?: FileDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'file_name': value['fileName'],
        'id': value['id'],
        'link': value['link'],
        'metadata': value['metadata'],
        's3_url': value['s3Url'],
        'size': value['size'],
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

