/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEventsData
 */
export interface GetEventsData {
    /**
     * The types of events to get. Any combination of file_uploaded, chunk_uploaded, chunk_action_failed, or chunk_updated. Leave undefined to get all events.
     * @type {Array<string>}
     * @memberof GetEventsData
     */
    eventTypes?: Array<string>;
    /**
     * The page number to get. Default is 1.
     * @type {number}
     * @memberof GetEventsData
     */
    page?: number;
    /**
     * The number of items per page. Default is 10.
     * @type {number}
     * @memberof GetEventsData
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the GetEventsData interface.
 */
export function instanceOfGetEventsData(value: object): boolean {
    return true;
}

export function GetEventsDataFromJSON(json: any): GetEventsData {
    return GetEventsDataFromJSONTyped(json, false);
}

export function GetEventsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEventsData {
    if (json == null) {
        return json;
    }
    return {
        
        'eventTypes': json['event_types'] == null ? undefined : json['event_types'],
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
    };
}

export function GetEventsDataToJSON(value?: GetEventsData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'event_types': value['eventTypes'],
        'page': value['page'],
        'page_size': value['pageSize'],
    };
}

