/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGroupsForChunksData
 */
export interface GetGroupsForChunksData {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetGroupsForChunksData
     */
    chunkIds: Array<string>;
}

/**
 * Check if a given object implements the GetGroupsForChunksData interface.
 */
export function instanceOfGetGroupsForChunksData(value: object): boolean {
    if (!('chunkIds' in value)) return false;
    return true;
}

export function GetGroupsForChunksDataFromJSON(json: any): GetGroupsForChunksData {
    return GetGroupsForChunksDataFromJSONTyped(json, false);
}

export function GetGroupsForChunksDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGroupsForChunksData {
    if (json == null) {
        return json;
    }
    return {
        
        'chunkIds': json['chunk_ids'],
    };
}

export function GetGroupsForChunksDataToJSON(value?: GetGroupsForChunksData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chunk_ids': value['chunkIds'],
    };
}

