/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScoreSlimChunks } from './ScoreSlimChunks';
import {
    ScoreSlimChunksFromJSON,
    ScoreSlimChunksFromJSONTyped,
    ScoreSlimChunksToJSON,
} from './ScoreSlimChunks';

/**
 * 
 * @export
 * @interface GroupScoreSlimChunks
 */
export interface GroupScoreSlimChunks {
    /**
     * 
     * @type {string}
     * @memberof GroupScoreSlimChunks
     */
    groupId: string;
    /**
     * 
     * @type {Array<ScoreSlimChunks>}
     * @memberof GroupScoreSlimChunks
     */
    metadata: Array<ScoreSlimChunks>;
}

/**
 * Check if a given object implements the GroupScoreSlimChunks interface.
 */
export function instanceOfGroupScoreSlimChunks(value: object): boolean {
    if (!('groupId' in value)) return false;
    if (!('metadata' in value)) return false;
    return true;
}

export function GroupScoreSlimChunksFromJSON(json: any): GroupScoreSlimChunks {
    return GroupScoreSlimChunksFromJSONTyped(json, false);
}

export function GroupScoreSlimChunksFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupScoreSlimChunks {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['group_id'],
        'metadata': ((json['metadata'] as Array<any>).map(ScoreSlimChunksFromJSON)),
    };
}

export function GroupScoreSlimChunksToJSON(value?: GroupScoreSlimChunks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'group_id': value['groupId'],
        'metadata': ((value['metadata'] as Array<any>).map(ScoreSlimChunksToJSON)),
    };
}

