/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChunkGroupAndFile } from './ChunkGroupAndFile';
import {
    ChunkGroupAndFileFromJSON,
    ChunkGroupAndFileFromJSONTyped,
    ChunkGroupAndFileToJSON,
} from './ChunkGroupAndFile';

/**
 * 
 * @export
 * @interface GroupData
 */
export interface GroupData {
    /**
     * 
     * @type {Array<ChunkGroupAndFile>}
     * @memberof GroupData
     */
    groups: Array<ChunkGroupAndFile>;
    /**
     * 
     * @type {number}
     * @memberof GroupData
     */
    totalPages: number;
}

/**
 * Check if a given object implements the GroupData interface.
 */
export function instanceOfGroupData(value: object): boolean {
    if (!('groups' in value)) return false;
    if (!('totalPages' in value)) return false;
    return true;
}

export function GroupDataFromJSON(json: any): GroupData {
    return GroupDataFromJSONTyped(json, false);
}

export function GroupDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupData {
    if (json == null) {
        return json;
    }
    return {
        
        'groups': ((json['groups'] as Array<any>).map(ChunkGroupAndFileFromJSON)),
        'totalPages': json['total_pages'],
    };
}

export function GroupDataToJSON(value?: GroupData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'groups': ((value['groups'] as Array<any>).map(ChunkGroupAndFileToJSON)),
        'total_pages': value['totalPages'],
    };
}

