/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvitationData
 */
export interface InvitationData {
    /**
     * The url of the app that the user will be directed to in order to set their password. Usually admin.trieve.ai, but may differ for local dev or self-hosted setups.
     * @type {string}
     * @memberof InvitationData
     */
    appUrl: string;
    /**
     * The email of the user to invite. Must be a valid email as they will be sent an email to register.
     * @type {string}
     * @memberof InvitationData
     */
    email: string;
    /**
     * The id of the organization to invite the user to.
     * @type {string}
     * @memberof InvitationData
     */
    organizationId: string;
    /**
     * The url that the user will be redirected to after setting their password.
     * @type {string}
     * @memberof InvitationData
     */
    redirectUri: string;
    /**
     * The role the user will have in the organization. 0 = User, 1 = Admin, 2 = Owner.
     * @type {number}
     * @memberof InvitationData
     */
    userRole: number;
}

/**
 * Check if a given object implements the InvitationData interface.
 */
export function instanceOfInvitationData(value: object): boolean {
    if (!('appUrl' in value)) return false;
    if (!('email' in value)) return false;
    if (!('organizationId' in value)) return false;
    if (!('redirectUri' in value)) return false;
    if (!('userRole' in value)) return false;
    return true;
}

export function InvitationDataFromJSON(json: any): InvitationData {
    return InvitationDataFromJSONTyped(json, false);
}

export function InvitationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationData {
    if (json == null) {
        return json;
    }
    return {
        
        'appUrl': json['app_url'],
        'email': json['email'],
        'organizationId': json['organization_id'],
        'redirectUri': json['redirect_uri'],
        'userRole': json['user_role'],
    };
}

export function InvitationDataToJSON(value?: InvitationData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'app_url': value['appUrl'],
        'email': value['email'],
        'organization_id': value['organizationId'],
        'redirect_uri': value['redirectUri'],
        'user_role': value['userRole'],
    };
}

