/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelFile
 */
export interface ModelFile {
    /**
     * 
     * @type {Date}
     * @memberof ModelFile
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    datasetId: string;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    link?: string;
    /**
     * 
     * @type {any}
     * @memberof ModelFile
     */
    metadata?: any;
    /**
     * 
     * @type {number}
     * @memberof ModelFile
     */
    size: number;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    tagSet?: string;
    /**
     * 
     * @type {Date}
     * @memberof ModelFile
     */
    timeStamp?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ModelFile
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ModelFile interface.
 */
export function instanceOfModelFile(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('datasetId' in value)) return false;
    if (!('fileName' in value)) return false;
    if (!('id' in value)) return false;
    if (!('size' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function ModelFileFromJSON(json: any): ModelFile {
    return ModelFileFromJSONTyped(json, false);
}

export function ModelFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelFile {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'datasetId': json['dataset_id'],
        'fileName': json['file_name'],
        'id': json['id'],
        'link': json['link'] == null ? undefined : json['link'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'size': json['size'],
        'tagSet': json['tag_set'] == null ? undefined : json['tag_set'],
        'timeStamp': json['time_stamp'] == null ? undefined : (new Date(json['time_stamp'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ModelFileToJSON(value?: ModelFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'dataset_id': value['datasetId'],
        'file_name': value['fileName'],
        'id': value['id'],
        'link': value['link'],
        'metadata': value['metadata'],
        'size': value['size'],
        'tag_set': value['tagSet'],
        'time_stamp': value['timeStamp'] == null ? undefined : ((value['timeStamp'] as any).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

