/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type RangeCondition
 * 
 * @export
 */
export type RangeCondition = number | string;

export function RangeConditionFromJSON(json: any): RangeCondition {
    return RangeConditionFromJSONTyped(json, false);
}

export function RangeConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RangeCondition {
    if (json == null) {
        return json;
    }
    return { ...numberFromJSONTyped(json, true), ...stringFromJSONTyped(json, true) };
}

export function RangeConditionToJSON(value?: RangeCondition | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfnumber(value)) {
        return numberToJSON(value as number);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

