/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RangeCondition } from './RangeCondition';
import {
    RangeConditionFromJSON,
    RangeConditionFromJSONTyped,
    RangeConditionToJSON,
} from './RangeCondition';

/**
 * 
 * @export
 * @interface Range
 */
export interface Range {
    /**
     * 
     * @type {RangeCondition}
     * @memberof Range
     */
    gt?: RangeCondition;
    /**
     * 
     * @type {RangeCondition}
     * @memberof Range
     */
    gte?: RangeCondition;
    /**
     * 
     * @type {RangeCondition}
     * @memberof Range
     */
    lt?: RangeCondition;
    /**
     * 
     * @type {RangeCondition}
     * @memberof Range
     */
    lte?: RangeCondition;
}

/**
 * Check if a given object implements the Range interface.
 */
export function instanceOfRange(value: object): boolean {
    return true;
}

export function RangeFromJSON(json: any): Range {
    return RangeFromJSONTyped(json, false);
}

export function RangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Range {
    if (json == null) {
        return json;
    }
    return {
        
        'gt': json['gt'] == null ? undefined : RangeConditionFromJSON(json['gt']),
        'gte': json['gte'] == null ? undefined : RangeConditionFromJSON(json['gte']),
        'lt': json['lt'] == null ? undefined : RangeConditionFromJSON(json['lt']),
        'lte': json['lte'] == null ? undefined : RangeConditionFromJSON(json['lte']),
    };
}

export function RangeToJSON(value?: Range | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'gt': RangeConditionToJSON(value['gt']),
        'gte': RangeConditionToJSON(value['gte']),
        'lt': RangeConditionToJSON(value['lt']),
        'lte': RangeConditionToJSON(value['lte']),
    };
}

