/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BatchQueuedChunkResponse } from './BatchQueuedChunkResponse';
import {
    instanceOfBatchQueuedChunkResponse,
    BatchQueuedChunkResponseFromJSON,
    BatchQueuedChunkResponseFromJSONTyped,
    BatchQueuedChunkResponseToJSON,
} from './BatchQueuedChunkResponse';
import type { SingleQueuedChunkResponse } from './SingleQueuedChunkResponse';
import {
    instanceOfSingleQueuedChunkResponse,
    SingleQueuedChunkResponseFromJSON,
    SingleQueuedChunkResponseFromJSONTyped,
    SingleQueuedChunkResponseToJSON,
} from './SingleQueuedChunkResponse';

/**
 * @type ReturnQueuedChunk
 * 
 * @export
 */
export type ReturnQueuedChunk = BatchQueuedChunkResponse | SingleQueuedChunkResponse;

export function ReturnQueuedChunkFromJSON(json: any): ReturnQueuedChunk {
    return ReturnQueuedChunkFromJSONTyped(json, false);
}

export function ReturnQueuedChunkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnQueuedChunk {
    if (json == null) {
        return json;
    }
    return BatchQueuedChunkResponseFromJSONTyped(json, true) || SingleQueuedChunkResponseFromJSONTyped(json, true);
}

export function ReturnQueuedChunkToJSON(value?: ReturnQueuedChunk | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfBatchQueuedChunkResponse(value)) {
        return BatchQueuedChunkResponseToJSON(value as BatchQueuedChunkResponse);
    }
    if (instanceOfSingleQueuedChunkResponse(value)) {
        return SingleQueuedChunkResponseToJSON(value as SingleQueuedChunkResponse);
    }

    return {};
}

