/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChunkMetadata } from './ChunkMetadata';
import {
    ChunkMetadataFromJSON,
    ChunkMetadataFromJSONTyped,
    ChunkMetadataToJSON,
} from './ChunkMetadata';

/**
 * 
 * @export
 * @interface ScoreChunkDTO
 */
export interface ScoreChunkDTO {
    /**
     * 
     * @type {Array<ChunkMetadata>}
     * @memberof ScoreChunkDTO
     */
    metadata: Array<ChunkMetadata>;
    /**
     * 
     * @type {number}
     * @memberof ScoreChunkDTO
     */
    score: number;
}

/**
 * Check if a given object implements the ScoreChunkDTO interface.
 */
export function instanceOfScoreChunkDTO(value: object): boolean {
    if (!('metadata' in value)) return false;
    if (!('score' in value)) return false;
    return true;
}

export function ScoreChunkDTOFromJSON(json: any): ScoreChunkDTO {
    return ScoreChunkDTOFromJSONTyped(json, false);
}

export function ScoreChunkDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreChunkDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': ((json['metadata'] as Array<any>).map(ChunkMetadataFromJSON)),
        'score': json['score'],
    };
}

export function ScoreChunkDTOToJSON(value?: ScoreChunkDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata': ((value['metadata'] as Array<any>).map(ChunkMetadataToJSON)),
        'score': value['score'],
    };
}

