/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SlimChunkMetadata } from './SlimChunkMetadata';
import {
    SlimChunkMetadataFromJSON,
    SlimChunkMetadataFromJSONTyped,
    SlimChunkMetadataToJSON,
} from './SlimChunkMetadata';

/**
 * 
 * @export
 * @interface ScoreSlimChunks
 */
export interface ScoreSlimChunks {
    /**
     * 
     * @type {Array<SlimChunkMetadata>}
     * @memberof ScoreSlimChunks
     */
    metadata: Array<SlimChunkMetadata>;
    /**
     * 
     * @type {number}
     * @memberof ScoreSlimChunks
     */
    score: number;
}

/**
 * Check if a given object implements the ScoreSlimChunks interface.
 */
export function instanceOfScoreSlimChunks(value: object): boolean {
    if (!('metadata' in value)) return false;
    if (!('score' in value)) return false;
    return true;
}

export function ScoreSlimChunksFromJSON(json: any): ScoreSlimChunks {
    return ScoreSlimChunksFromJSONTyped(json, false);
}

export function ScoreSlimChunksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreSlimChunks {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': ((json['metadata'] as Array<any>).map(SlimChunkMetadataFromJSON)),
        'score': json['score'],
    };
}

export function ScoreSlimChunksToJSON(value?: ScoreSlimChunks | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata': ((value['metadata'] as Array<any>).map(SlimChunkMetadataToJSON)),
        'score': value['score'],
    };
}

