/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChunkGroup } from './ChunkGroup';
import {
    ChunkGroupFromJSON,
    ChunkGroupFromJSONTyped,
    ChunkGroupToJSON,
} from './ChunkGroup';
import type { ScoreSlimChunks } from './ScoreSlimChunks';
import {
    ScoreSlimChunksFromJSON,
    ScoreSlimChunksFromJSONTyped,
    ScoreSlimChunksToJSON,
} from './ScoreSlimChunks';

/**
 * 
 * @export
 * @interface SearchWithinGroupSlimResults
 */
export interface SearchWithinGroupSlimResults {
    /**
     * 
     * @type {Array<ScoreSlimChunks>}
     * @memberof SearchWithinGroupSlimResults
     */
    bookmarks: Array<ScoreSlimChunks>;
    /**
     * 
     * @type {ChunkGroup}
     * @memberof SearchWithinGroupSlimResults
     */
    group: ChunkGroup;
    /**
     * 
     * @type {number}
     * @memberof SearchWithinGroupSlimResults
     */
    totalPages: number;
}

/**
 * Check if a given object implements the SearchWithinGroupSlimResults interface.
 */
export function instanceOfSearchWithinGroupSlimResults(value: object): boolean {
    if (!('bookmarks' in value)) return false;
    if (!('group' in value)) return false;
    if (!('totalPages' in value)) return false;
    return true;
}

export function SearchWithinGroupSlimResultsFromJSON(json: any): SearchWithinGroupSlimResults {
    return SearchWithinGroupSlimResultsFromJSONTyped(json, false);
}

export function SearchWithinGroupSlimResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchWithinGroupSlimResults {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarks': ((json['bookmarks'] as Array<any>).map(ScoreSlimChunksFromJSON)),
        'group': ChunkGroupFromJSON(json['group']),
        'totalPages': json['total_pages'],
    };
}

export function SearchWithinGroupSlimResultsToJSON(value?: SearchWithinGroupSlimResults | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bookmarks': ((value['bookmarks'] as Array<any>).map(ScoreSlimChunksToJSON)),
        'group': ChunkGroupToJSON(value['group']),
        'total_pages': value['totalPages'],
    };
}

