/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupScoreChunk } from './GroupScoreChunk';
import {
    GroupScoreChunkFromJSON,
    GroupScoreChunkFromJSONTyped,
    GroupScoreChunkToJSON,
} from './GroupScoreChunk';

/**
 * 
 * @export
 * @interface SearchOverGroupsResults
 */
export interface SearchOverGroupsResults {
    /**
     * 
     * @type {Array<GroupScoreChunk>}
     * @memberof SearchOverGroupsResults
     */
    groupChunks: Array<GroupScoreChunk>;
    /**
     * 
     * @type {number}
     * @memberof SearchOverGroupsResults
     */
    totalChunkPages: number;
}

/**
 * Check if a given object implements the SearchOverGroupsResults interface.
 */
export function instanceOfSearchOverGroupsResults(value: object): boolean {
    if (!('groupChunks' in value)) return false;
    if (!('totalChunkPages' in value)) return false;
    return true;
}

export function SearchOverGroupsResultsFromJSON(json: any): SearchOverGroupsResults {
    return SearchOverGroupsResultsFromJSONTyped(json, false);
}

export function SearchOverGroupsResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchOverGroupsResults {
    if (json == null) {
        return json;
    }
    return {
        
        'groupChunks': ((json['group_chunks'] as Array<any>).map(GroupScoreChunkFromJSON)),
        'totalChunkPages': json['total_chunk_pages'],
    };
}

export function SearchOverGroupsResultsToJSON(value?: SearchOverGroupsResults | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'group_chunks': ((value['groupChunks'] as Array<any>).map(GroupScoreChunkToJSON)),
        'total_chunk_pages': value['totalChunkPages'],
    };
}

