/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScoreChunkDTO } from './ScoreChunkDTO';
import {
    ScoreChunkDTOFromJSON,
    ScoreChunkDTOFromJSONTyped,
    ScoreChunkDTOToJSON,
} from './ScoreChunkDTO';

/**
 * 
 * @export
 * @interface SearchChunkQueryResponseBody
 */
export interface SearchChunkQueryResponseBody {
    /**
     * 
     * @type {Array<ScoreChunkDTO>}
     * @memberof SearchChunkQueryResponseBody
     */
    scoreChunks: Array<ScoreChunkDTO>;
    /**
     * 
     * @type {number}
     * @memberof SearchChunkQueryResponseBody
     */
    totalChunkPages: number;
}

/**
 * Check if a given object implements the SearchChunkQueryResponseBody interface.
 */
export function instanceOfSearchChunkQueryResponseBody(value: object): boolean {
    if (!('scoreChunks' in value)) return false;
    if (!('totalChunkPages' in value)) return false;
    return true;
}

export function SearchChunkQueryResponseBodyFromJSON(json: any): SearchChunkQueryResponseBody {
    return SearchChunkQueryResponseBodyFromJSONTyped(json, false);
}

export function SearchChunkQueryResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchChunkQueryResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        'scoreChunks': ((json['score_chunks'] as Array<any>).map(ScoreChunkDTOFromJSON)),
        'totalChunkPages': json['total_chunk_pages'],
    };
}

export function SearchChunkQueryResponseBodyToJSON(value?: SearchChunkQueryResponseBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'score_chunks': ((value['scoreChunks'] as Array<any>).map(ScoreChunkDTOToJSON)),
        'total_chunk_pages': value['totalChunkPages'],
    };
}

