/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetUserApiKeyResponse
 */
export interface SetUserApiKeyResponse {
    /**
     * The api key which was created. This is the value which should be used in the Authorization header.
     * @type {string}
     * @memberof SetUserApiKeyResponse
     */
    apiKey: string;
}

/**
 * Check if a given object implements the SetUserApiKeyResponse interface.
 */
export function instanceOfSetUserApiKeyResponse(value: object): boolean {
    if (!('apiKey' in value)) return false;
    return true;
}

export function SetUserApiKeyResponseFromJSON(json: any): SetUserApiKeyResponse {
    return SetUserApiKeyResponseFromJSONTyped(json, false);
}

export function SetUserApiKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetUserApiKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'],
    };
}

export function SetUserApiKeyResponseToJSON(value?: SetUserApiKeyResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'api_key': value['apiKey'],
    };
}

