/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetUserApiKeyRequest
 */
export interface SetUserApiKeyRequest {
    /**
     * The name which will be assigned to the new api key.
     * @type {string}
     * @memberof SetUserApiKeyRequest
     */
    name: string;
    /**
     * The role which will be assigned to the new api key. Either 0 (read), 1 (read and write at the level of the currently auth'ed user). The auth'ed user must have a role greater than or equal to the role being assigned which means they must be an admin (1) or owner (2) of the organization to assign write permissions with a role of 1.
     * @type {number}
     * @memberof SetUserApiKeyRequest
     */
    role: number;
}

/**
 * Check if a given object implements the SetUserApiKeyRequest interface.
 */
export function instanceOfSetUserApiKeyRequest(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('role' in value)) return false;
    return true;
}

export function SetUserApiKeyRequestFromJSON(json: any): SetUserApiKeyRequest {
    return SetUserApiKeyRequestFromJSONTyped(json, false);
}

export function SetUserApiKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetUserApiKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'role': json['role'],
    };
}

export function SetUserApiKeyRequestToJSON(value?: SetUserApiKeyRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'role': value['role'],
    };
}

