/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChunkMetadata } from './ChunkMetadata';
import {
    ChunkMetadataFromJSON,
    ChunkMetadataFromJSONTyped,
    ChunkMetadataToJSON,
} from './ChunkMetadata';

/**
 * 
 * @export
 * @interface SingleQueuedChunkResponse
 */
export interface SingleQueuedChunkResponse {
    /**
     * 
     * @type {ChunkMetadata}
     * @memberof SingleQueuedChunkResponse
     */
    chunkMetadata: ChunkMetadata;
    /**
     * The current position the last access item is in the queue
     * @type {number}
     * @memberof SingleQueuedChunkResponse
     */
    posInQueue: number;
}

/**
 * Check if a given object implements the SingleQueuedChunkResponse interface.
 */
export function instanceOfSingleQueuedChunkResponse(value: object): boolean {
    if (!('chunkMetadata' in value)) return false;
    if (!('posInQueue' in value)) return false;
    return true;
}

export function SingleQueuedChunkResponseFromJSON(json: any): SingleQueuedChunkResponse {
    return SingleQueuedChunkResponseFromJSONTyped(json, false);
}

export function SingleQueuedChunkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleQueuedChunkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chunkMetadata': ChunkMetadataFromJSON(json['chunk_metadata']),
        'posInQueue': json['pos_in_queue'],
    };
}

export function SingleQueuedChunkResponseToJSON(value?: SingleQueuedChunkResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chunk_metadata': ChunkMetadataToJSON(value['chunkMetadata']),
        'pos_in_queue': value['posInQueue'],
    };
}

