/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SlimChunkMetadata
 */
export interface SlimChunkMetadata {
    /**
     * 
     * @type {Date}
     * @memberof SlimChunkMetadata
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SlimChunkMetadata
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SlimChunkMetadata
     */
    link?: string;
    /**
     * 
     * @type {any}
     * @memberof SlimChunkMetadata
     */
    metadata?: any;
    /**
     * 
     * @type {string}
     * @memberof SlimChunkMetadata
     */
    qdrantPointId?: string;
    /**
     * 
     * @type {string}
     * @memberof SlimChunkMetadata
     */
    tagSet?: string;
    /**
     * 
     * @type {Date}
     * @memberof SlimChunkMetadata
     */
    timeStamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof SlimChunkMetadata
     */
    trackingId?: string;
    /**
     * 
     * @type {Date}
     * @memberof SlimChunkMetadata
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof SlimChunkMetadata
     */
    weight: number;
}

/**
 * Check if a given object implements the SlimChunkMetadata interface.
 */
export function instanceOfSlimChunkMetadata(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('id' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('weight' in value)) return false;
    return true;
}

export function SlimChunkMetadataFromJSON(json: any): SlimChunkMetadata {
    return SlimChunkMetadataFromJSONTyped(json, false);
}

export function SlimChunkMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlimChunkMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'link': json['link'] == null ? undefined : json['link'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'qdrantPointId': json['qdrant_point_id'] == null ? undefined : json['qdrant_point_id'],
        'tagSet': json['tag_set'] == null ? undefined : json['tag_set'],
        'timeStamp': json['time_stamp'] == null ? undefined : (new Date(json['time_stamp'])),
        'trackingId': json['tracking_id'] == null ? undefined : json['tracking_id'],
        'updatedAt': (new Date(json['updated_at'])),
        'weight': json['weight'],
    };
}

export function SlimChunkMetadataToJSON(value?: SlimChunkMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'id': value['id'],
        'link': value['link'],
        'metadata': value['metadata'],
        'qdrant_point_id': value['qdrantPointId'],
        'tag_set': value['tagSet'],
        'time_stamp': value['timeStamp'] == null ? undefined : ((value['timeStamp'] as any).toISOString()),
        'tracking_id': value['trackingId'],
        'updated_at': ((value['updatedAt']).toISOString()),
        'weight': value['weight'],
    };
}

