/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SlimGroup
 */
export interface SlimGroup {
    /**
     * 
     * @type {string}
     * @memberof SlimGroup
     */
    datasetId: string;
    /**
     * 
     * @type {string}
     * @memberof SlimGroup
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SlimGroup
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof SlimGroup
     */
    ofCurrentDataset: boolean;
}

/**
 * Check if a given object implements the SlimGroup interface.
 */
export function instanceOfSlimGroup(value: object): boolean {
    if (!('datasetId' in value)) return false;
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('ofCurrentDataset' in value)) return false;
    return true;
}

export function SlimGroupFromJSON(json: any): SlimGroup {
    return SlimGroupFromJSONTyped(json, false);
}

export function SlimGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlimGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'datasetId': json['dataset_id'],
        'id': json['id'],
        'name': json['name'],
        'ofCurrentDataset': json['of_current_dataset'],
    };
}

export function SlimGroupToJSON(value?: SlimGroup | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dataset_id': value['datasetId'],
        'id': value['id'],
        'name': value['name'],
        'of_current_dataset': value['ofCurrentDataset'],
    };
}

