/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripePlan
 */
export interface StripePlan {
    /**
     * 
     * @type {number}
     * @memberof StripePlan
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof StripePlan
     */
    chunkCount: number;
    /**
     * 
     * @type {Date}
     * @memberof StripePlan
     */
    createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof StripePlan
     */
    datasetCount: number;
    /**
     * 
     * @type {number}
     * @memberof StripePlan
     */
    fileStorage: number;
    /**
     * 
     * @type {string}
     * @memberof StripePlan
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof StripePlan
     */
    messageCount: number;
    /**
     * 
     * @type {string}
     * @memberof StripePlan
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StripePlan
     */
    stripeId: string;
    /**
     * 
     * @type {Date}
     * @memberof StripePlan
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof StripePlan
     */
    userCount: number;
}

/**
 * Check if a given object implements the StripePlan interface.
 */
export function instanceOfStripePlan(value: object): boolean {
    if (!('amount' in value)) return false;
    if (!('chunkCount' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('datasetCount' in value)) return false;
    if (!('fileStorage' in value)) return false;
    if (!('id' in value)) return false;
    if (!('messageCount' in value)) return false;
    if (!('name' in value)) return false;
    if (!('stripeId' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('userCount' in value)) return false;
    return true;
}

export function StripePlanFromJSON(json: any): StripePlan {
    return StripePlanFromJSONTyped(json, false);
}

export function StripePlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripePlan {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'chunkCount': json['chunk_count'],
        'createdAt': (new Date(json['created_at'])),
        'datasetCount': json['dataset_count'],
        'fileStorage': json['file_storage'],
        'id': json['id'],
        'messageCount': json['message_count'],
        'name': json['name'],
        'stripeId': json['stripe_id'],
        'updatedAt': (new Date(json['updated_at'])),
        'userCount': json['user_count'],
    };
}

export function StripePlanToJSON(value?: StripePlan | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'chunk_count': value['chunkCount'],
        'created_at': ((value['createdAt']).toISOString()),
        'dataset_count': value['datasetCount'],
        'file_storage': value['fileStorage'],
        'id': value['id'],
        'message_count': value['messageCount'],
        'name': value['name'],
        'stripe_id': value['stripeId'],
        'updated_at': ((value['updatedAt']).toISOString()),
        'user_count': value['userCount'],
    };
}

