/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuggestedQueriesRequest
 */
export interface SuggestedQueriesRequest {
    /**
     * The query to base the generated suggested queries off of.
     * @type {string}
     * @memberof SuggestedQueriesRequest
     */
    query: string;
}

/**
 * Check if a given object implements the SuggestedQueriesRequest interface.
 */
export function instanceOfSuggestedQueriesRequest(value: object): boolean {
    if (!('query' in value)) return false;
    return true;
}

export function SuggestedQueriesRequestFromJSON(json: any): SuggestedQueriesRequest {
    return SuggestedQueriesRequestFromJSONTyped(json, false);
}

export function SuggestedQueriesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestedQueriesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
    };
}

export function SuggestedQueriesRequestToJSON(value?: SuggestedQueriesRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'query': value['query'],
    };
}

