/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Topic
 */
export interface Topic {
    /**
     * 
     * @type {Date}
     * @memberof Topic
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    datasetId: string;
    /**
     * 
     * @type {boolean}
     * @memberof Topic
     */
    deleted: boolean;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof Topic
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    userId: string;
}

/**
 * Check if a given object implements the Topic interface.
 */
export function instanceOfTopic(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('datasetId' in value)) return false;
    if (!('deleted' in value)) return false;
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('userId' in value)) return false;
    return true;
}

export function TopicFromJSON(json: any): Topic {
    return TopicFromJSONTyped(json, false);
}

export function TopicFromJSONTyped(json: any, ignoreDiscriminator: boolean): Topic {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'datasetId': json['dataset_id'],
        'deleted': json['deleted'],
        'id': json['id'],
        'name': json['name'],
        'updatedAt': (new Date(json['updated_at'])),
        'userId': json['user_id'],
    };
}

export function TopicToJSON(value?: Topic | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'dataset_id': value['datasetId'],
        'deleted': value['deleted'],
        'id': value['id'],
        'name': value['name'],
        'updated_at': ((value['updatedAt']).toISOString()),
        'user_id': value['userId'],
    };
}

