/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTopicData
 */
export interface UpdateTopicData {
    /**
     * The new name of the topic. A name is not generated from this field, it is used as-is.
     * @type {string}
     * @memberof UpdateTopicData
     */
    name: string;
    /**
     * The id of the topic to target.
     * @type {string}
     * @memberof UpdateTopicData
     */
    topicId: string;
}

/**
 * Check if a given object implements the UpdateTopicData interface.
 */
export function instanceOfUpdateTopicData(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('topicId' in value)) return false;
    return true;
}

export function UpdateTopicDataFromJSON(json: any): UpdateTopicData {
    return UpdateTopicDataFromJSONTyped(json, false);
}

export function UpdateTopicDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTopicData {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'topicId': json['topic_id'],
    };
}

export function UpdateTopicDataToJSON(value?: UpdateTopicData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'topic_id': value['topicId'],
    };
}

