/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOrganizationData
 */
export interface UpdateOrganizationData {
    /**
     * The new name of the organization. If not provided, the name will not be updated.
     * @type {string}
     * @memberof UpdateOrganizationData
     */
    name?: string;
    /**
     * The id of the organization to update.
     * @type {string}
     * @memberof UpdateOrganizationData
     */
    organizationId: string;
}

/**
 * Check if a given object implements the UpdateOrganizationData interface.
 */
export function instanceOfUpdateOrganizationData(value: object): boolean {
    if (!('organizationId' in value)) return false;
    return true;
}

export function UpdateOrganizationDataFromJSON(json: any): UpdateOrganizationData {
    return UpdateOrganizationDataFromJSONTyped(json, false);
}

export function UpdateOrganizationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrganizationData {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'organizationId': json['organization_id'],
    };
}

export function UpdateOrganizationDataToJSON(value?: UpdateOrganizationData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'organization_id': value['organizationId'],
    };
}

