/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateGroupByTrackingIDData
 */
export interface UpdateGroupByTrackingIDData {
    /**
     * Description to assign to the chunk_group. Convenience field for you to avoid having to remember what the group is for. If not provided, the description will not be updated.
     * @type {string}
     * @memberof UpdateGroupByTrackingIDData
     */
    description?: string;
    /**
     * Optional metadata to assign to the chunk_group. This is a JSON object that can store any additional information you want to associate with the chunks inside of the chunk_group.
     * @type {any}
     * @memberof UpdateGroupByTrackingIDData
     */
    metadata?: any;
    /**
     * Name to assign to the chunk_group. Does not need to be unique. If not provided, the name will not be updated.
     * @type {string}
     * @memberof UpdateGroupByTrackingIDData
     */
    name?: string;
    /**
     * Optional tags to assign to the chunk_group. This is a list of strings that can be used to categorize the chunks inside the chunk_group.
     * @type {Array<string>}
     * @memberof UpdateGroupByTrackingIDData
     */
    tagSet?: Array<string>;
    /**
     * Tracking Id of the chunk_group to update.
     * @type {string}
     * @memberof UpdateGroupByTrackingIDData
     */
    trackingId: string;
}

/**
 * Check if a given object implements the UpdateGroupByTrackingIDData interface.
 */
export function instanceOfUpdateGroupByTrackingIDData(value: object): boolean {
    if (!('trackingId' in value)) return false;
    return true;
}

export function UpdateGroupByTrackingIDDataFromJSON(json: any): UpdateGroupByTrackingIDData {
    return UpdateGroupByTrackingIDDataFromJSONTyped(json, false);
}

export function UpdateGroupByTrackingIDDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGroupByTrackingIDData {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'] == null ? undefined : json['name'],
        'tagSet': json['tag_set'] == null ? undefined : json['tag_set'],
        'trackingId': json['tracking_id'],
    };
}

export function UpdateGroupByTrackingIDDataToJSON(value?: UpdateGroupByTrackingIDData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'metadata': value['metadata'],
        'name': value['name'],
        'tag_set': value['tagSet'],
        'tracking_id': value['trackingId'],
    };
}

