/* tslint:disable */
/* eslint-disable */
/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.6.9
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateChunkGroupData
 */
export interface UpdateChunkGroupData {
    /**
     * Description to assign to the chunk_group. Convenience field for you to avoid having to remember what the group is for. If not provided, the description will not be updated.
     * @type {string}
     * @memberof UpdateChunkGroupData
     */
    description?: string;
    /**
     * Id of the chunk_group to update.
     * @type {string}
     * @memberof UpdateChunkGroupData
     */
    groupId?: string;
    /**
     * Optional metadata to assign to the chunk_group. This is a JSON object that can store any additional information you want to associate with the chunks inside of the chunk_group.
     * @type {any}
     * @memberof UpdateChunkGroupData
     */
    metadata?: any;
    /**
     * Name to assign to the chunk_group. Does not need to be unique. If not provided, the name will not be updated.
     * @type {string}
     * @memberof UpdateChunkGroupData
     */
    name?: string;
    /**
     * Optional tags to assign to the chunk_group. This is a list of strings that can be used to categorize the chunks inside the chunk_group.
     * @type {Array<string>}
     * @memberof UpdateChunkGroupData
     */
    tagSet?: Array<string>;
    /**
     * Tracking Id of the chunk_group to update.
     * @type {string}
     * @memberof UpdateChunkGroupData
     */
    trackingId?: string;
}

/**
 * Check if a given object implements the UpdateChunkGroupData interface.
 */
export function instanceOfUpdateChunkGroupData(value: object): boolean {
    return true;
}

export function UpdateChunkGroupDataFromJSON(json: any): UpdateChunkGroupData {
    return UpdateChunkGroupDataFromJSONTyped(json, false);
}

export function UpdateChunkGroupDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateChunkGroupData {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'] == null ? undefined : json['name'],
        'tagSet': json['tag_set'] == null ? undefined : json['tag_set'],
        'trackingId': json['tracking_id'] == null ? undefined : json['tracking_id'],
    };
}

export function UpdateChunkGroupDataToJSON(value?: UpdateChunkGroupData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'group_id': value['groupId'],
        'metadata': value['metadata'],
        'name': value['name'],
        'tag_set': value['tagSet'],
        'tracking_id': value['trackingId'],
    };
}

